### ISSUE TITLE
Step by Step

### ISSUE THREAD

**Issue by monza258** [anhem/lametric-hue-temperature#1]
Hey,

Can you take a step by step guide?

**Comment by anhem** [comment]
Have your looked at the [readme](https://github.com/anhem/lametric-hue-temperature/blob/master/README.md)? There is a step-by-step guide there. You might need some coding experience to be able to follow them.

**Comment by monza258** [comment]
I did not understand it. If you would help me, I would be very grateful.

**Comment by anhem** [comment]
This was never intended to be user-friendly, you need some developer experience. But here is some more information to point you in the right direction:

* You need to know the IP-address of your Philips Hue Bridge (go to https://discovery.meethue.com/). 
You also need an API-key. Go to http://your-philips-hue-bridge-ip/debug/clip.html and enter /api in the URL and {"devicetype":"lametric-hue-temp#server"} in the message body. Then go and press the physical button on your Philips Hue Bridge, and then click on the post button. The username is your api-key.
It should look like this if successful: https://www.developers.meethue.com/sites/default/files/SuccessResponse.png. This is what step 1 from the readme is about.

* You need your own server on your home network to run this application from. Your server needs to have Node and npm installed. 
After that you can do step 3 from the readme. If successful you should have a new folder called dist with some .js files in it. It is app.js

* The application is written to be executed on regular intervals, for example as a scheduled cron-job. 
I.e. it will shutdown once it has completed its task, and needs to be started again for the temperature data to be updated. This is what step 4-5 from the readme is about.

* The application will upon execution connect to your Philips Hue Bridge and ask it for all Motion Sensors. 
Once the bridge has responded the application will filter out temperature data and push that information to LaMetric servers (not your LaMetric Time device). 

* You need to create an app at LaMetric that can receive the temperature data and to display the information on your LaMetric Time device. This is what step 2 from the readme is about

**Comment by monza258** [comment]
Thanks first.

Today I will check this.
Can you tell how I can find the LAMETRIC_PUSH_URL ?

I have installed on my Raspberry PI.

**Comment by anhem** [comment]
Go to https://developer.lametric.com/applications/create and create a LaMetric Indicator App with Push communication and publish it as a private app. Now you should have your LAMETRIC_ACCESS_TOKEN and LAMETRIC_PUSH_URL

**Comment by monza258** [comment]
Is it right:
Thats my file of /home/pi

#!/usr/bin/env bash
HUE_API_KEY="username": "xxxxxxxxxxxxxxxxxxxxx" \
HUE_BRIDGE_IP=192.168.0.30 \
LAMETRIC_ACCESS_TOKEN=xxxxxxxxxxxx \
LAMETRIC_PUSH_URL=https://developer.lametric.com/api/v1/dev/widget/update/com.lametric.a7e859xxxxxxxxxx/1 \
/usr/bin/node /huelametric/lametric-hue-temperature/dist/app.js 2>&1

**Comment by anhem** [comment]
It should look like this:

#!/usr/bin/env bash
HUE_API_KEY=xxxxxxxxxxxxxxxxxxxxx \\
HUE_BRIDGE_IP=192.168.0.30 \\
LAMETRIC_ACCESS_TOKEN=xxxxxxxxxxxx \\
LAMETRIC_PUSH_URL=https://developer.lametric.com/api/v1/dev/widget/update/com.lametric.a7e859xxxxxxxxxx/1 \\
/usr/bin/node /huelametric/lametric-hue-temperature/dist/app.js 2>&1

To test that it works you can execute `./lametric-hue-temperature.cron.sh`. That should give you something similar to this if it works:
`
Message: {"frames":[{"text":"Ha 20.8","icon":"2056","index":0,"duration":4000},{"text":"Ki 21.5","icon":"2056","index":1,"duration":4000},{"text":"Be 21.5","icon":"2056","index":2,"duration":4000}]}
`

**Comment by monza258** [comment]
sorry about it: Thanks for you help:

Thats so true: ?

pi@raspberrypi:~ $ ./lametric-hue-temperature.cron.sh
-bash: ./lametric-hue-temperature.cron.sh: Keine Berechtigung
No Permissions? 

pi@raspberrypi:~ $ ./lametric-hue-temperature.cron.sh
./lametric-hue-temperature.cron.sh: Zeile 2: /usr/bin/node: Datei oder Verzeichnis nicht gefunden


pi@raspberrypi:~ $ npm start
npm ERR! path /home/pi/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open '/home/pi/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2018-10-06T19_30_26_694Z-debug.log

Is there any Problem?

**Comment by monza258** [comment]
pls help me.

Any idea about it?

**Comment by monza258** [comment]
pi@raspberrypi:~ $ ./lametric-hue-temperature.cron.sh
/home/pi/lametric-hue-temperature/app/app.js:1
(function (exports, require, module, __filename, __dirname) { import hueService from "./hueService";
                                                                     ^^^^^^^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:74:7)
    at createScript (vm.js:246:10)
    at Object.runInThisContext (vm.js:298:10)
    at Module._compile (internal/modules/cjs/loader.js:670:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:10)
    at startup (internal/bootstrap/node.js:238:19)

**Comment by anhem** [comment]
I've updated the readme and "fixed" lametric-hue-temperature.cron.sh, it should work better now. So have a look at the new readme and also use the new lametric-hue-temperature.cron.sh
